Add : 메인카테고리 & 좋아요 기능구현
wecode-bootcamp-korea/15-2nd-anotherclass101-backend pull request #3
Opened 2021-01-03 09:01 UTC by YEOJU-SEOK

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 메인카테고리&좋아요 기능구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-매인화면 호출 API구현
-좋아요 기능 구현
-unit test 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-test.py에서 메인화면 호출 관련된 unit test를 작성했습니다만, 계속 오류가 발생해서 이부분에 대해 리뷰를 받고 싶습니다.
![스크린샷 2021-01-03 18 01 01](https://user-images.githubusercontent.com/71719160/103475095-a8d43700-4ded-11eb-8546-2a3da21d5025.png)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-04 02:54 UTC, lordmyshepherd requested changes

2021-01-04 02:54 UTC, lordmyshepherd commented on \
> +import json
해당 파일 명이 `\`로 되어 있네요. 확인해주세요~

2021-01-04 02:54 UTC, lordmyshepherd commented on product/tests.py
> +    def set_up_database(self):
```suggestion
    def set_up(self):
```

2021-01-04 02:54 UTC, lordmyshepherd commented on product/tests.py
> +from django.db import connection
connection 모듈은 어디서 사용하는건가요?

2021-01-04 02:54 UTC, lordmyshepherd commented on product/tests.py
> +from product.models import *
import할 때 `*`은 사용하지 않도록 하는게 좋습니다.
이유는 다른 모듈에서 Class를 import하면 `import 문`이 실행될 때, 모듈에 있는 모든 Class, function을 생성합니다.
그렇기 때문에 사용하지 않는 객체를 만들어서 메모리를 낭비하지 않도록 주의하는 것이 좋습니다.

2021-01-04 02:54 UTC, lordmyshepherd commented on product/views.py
> +   # @id_auth
나중에 해야될 일은 주석이 아니라 `TODO`를 사용해주세요.
```suggestion
   # TODO : Add @id_auth
```

2021-01-04 02:54 UTC, lordmyshepherd commented on product/views.py
> +        print(a)
프린트는 지워주세요.

2021-01-04 02:54 UTC, lordmyshepherd commented on product/views.py
> +        products    = Product.objects.prefetch_related('course_set','course_set__courserequest_set').select_related('sub_category','creator', 'creator__user').filter(sub_category__in = subcategory)
45, 46 line의 코드 없이 Product class에서 접근해서 원하는 데이터를 가져올 수 있습니다.
한줄로 줄여보세요~

2021-01-04 02:54 UTC, lordmyshepherd commented on product/views.py
> +        text = [{
함수가 실행되고 반환하는 값이 list이므로, results라는 변수명이 더 적합할 것 같습니다.
```suggestion
        results = [{
```

2021-01-04 02:54 UTC, lordmyshepherd commented on product/views.py
> +            'like'         : ProductLike.objects.filter(product_id = product.id).count()
여기도 이미 caching해서 가져온 값을 사용하는게 좋을 것 같습니다. 
```suggestion
            'like'         : product..
```

2021-01-04 02:54 UTC, lordmyshepherd commented on product/views.py
> +        a = [product.course_set.get().courserequest_set.get().name for product in products]
어디서 사용하는 코드인가요?
```suggestion
        a = [product.course_set.get().courserequest_set.get().name for product in products]
```

2021-01-04 02:54 UTC, lordmyshepherd commented on product/views.py
> +           # user = request.user
```suggestion
           # TODO: Add user = request.user in 22line 
```

2021-01-05 08:15 UTC, lordmyshepherd requested changes

2021-01-05 08:15 UTC, lordmyshepherd commented on product/tests.py
> +        client = Client()
setup에서 client 객체를 만들었는데, `test_couselistview_get`에서 사용하지 않고 다시 생성하는 이유가 있나요?

2021-01-05 08:15 UTC, lordmyshepherd commented on product/views.py
> +        print(product_pk)
프린트문을 지워주세요~
```suggestion

```

2021-01-05 08:15 UTC, lordmyshepherd commented on product/views.py
> +    def post(self, request, product_pk):
Restful API 조건 기억하시나요?
`POST`  `/like/<int:product_pk>`와 같이 앤드포인트를 구현하게되면 아래와 같은 문제가 발생합니다.

엔드포인트를 호출할 때 `/like/1`와 같이 호출할텐데, 이때 1은 당연히 course like 데이터 중에 1번 데이터를 의미하는 것 처럼보이는데 실제로는 product_id를 받고 있습니다. restful api는 `uri`를 통해서 자원을 명확하게 알 수 있어야 합니다.

그렇기 때문에 product_id는 body에 담아서 요청을 처리하도록 수정해주세요. urlconf도 마찬가지로 수정해주세요~

2021-01-05 08:15 UTC, lordmyshepherd commented on product/views.py
> +class CourseLikeView(View):
정확히는 ProductLike 객체 관련된 코드이므로 이름을 수정해주는게 좋을 것 같습니다.
```suggestion
class ProductLikeView(View):
```

2021-01-05 08:15 UTC, lordmyshepherd commented on product/views.py
> +            return JsonResponse({'message':'SUCCESS'}, status = 201)
중복 체크를 해야되는 경우 exists() method를 사용하는게 실행 속도 측면에서 빠릅니다.
```suggestion
            if ProductLike.objects.filter(user = user, product = course).exists()
                    return JsonResponse({'message':'ALREADY_LIKE'},status = 400)
            ProductLike.objects.create(..)
            return JsonResponse({'message':'SUCCESS'}, status = 201)
```

2021-01-05 08:15 UTC, lordmyshepherd commented on product/views.py
> +        course_like = ProductLike.objects.get(user = user, product = course)
get() 사용할 경우 발생할 수 있는 error에 대한 고려가 필요해 보입니다.

2021-01-05 08:15 UTC, lordmyshepherd commented on product/views.py
> +        course      = Product.objects.get(id = product_pk)
여기서는 product_id를 받아서 `ProductLike` 데이터를 지우는게 아니라 ProductLike의 고유 id를 받아서 삭제하도록 수정해주세요.

2021-01-07 10:18 UTC, YEOJU-SEOK commented on product/tests.py
> +        client = Client()
해당 내용 삭제하였습니다

2021-01-07 10:18 UTC, YEOJU-SEOK commented on product/views.py
> +        print(product_pk)
지웠습니다 감사합니다🙏

2021-01-07 10:18 UTC, YEOJU-SEOK commented on product/views.py
> +    def post(self, request, product_pk):
반영했습니다!

2021-01-07 10:19 UTC, YEOJU-SEOK commented on product/views.py
> +class CourseLikeView(View):
수정완료했습니다

2021-01-07 10:19 UTC, YEOJU-SEOK commented on product/views.py
> +            return JsonResponse({'message':'SUCCESS'}, status = 201)
반영했습니다 감사합니다

2021-01-07 10:24 UTC, YEOJU-SEOK commented on product/views.py
> +        course_like = ProductLike.objects.get(user = user, product = course)
except통해 적용했습니다

2021-01-07 10:24 UTC, YEOJU-SEOK commented on product/views.py
> +        course      = Product.objects.get(id = product_pk)
반영했습니다

2021-01-07 11:40 UTC, ulfrid commented
LGTM.

2021-01-07 11:40 UTC, merged